# ============================================
# SPARK MASTER
# ============================================
apiVersion: v1
kind: Service
metadata:
  name: spark-master
spec:
  type: ClusterIP
  ports:
    - port: 7077
      targetPort: 7077
      name: spark
    - port: 8080
      targetPort: 8080
      name: web-ui
  selector:
    app: spark-master
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-master
  template:
    metadata:
      labels:
        app: spark-master
    spec:
      containers:
      - name: spark-master
        image: apache/spark:3.4.1
        command: ["/opt/spark/bin/spark-class"]
        args: ["org.apache.spark.deploy.master.Master"]
        ports:
        - containerPort: 7077
          name: spark
        - containerPort: 8080
          name: web-ui
        env:
        - name: SPARK_MASTER_HOST
          value: "0.0.0.0"  # ✅ FIX
        - name: SPARK_MASTER_PORT
          value: "7077"
        - name: SPARK_MASTER_WEBUI_PORT
          value: "8080"
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
---
# ============================================
# SPARK WORKERS
# ============================================
apiVersion: v1
kind: Service
metadata:
  name: spark-worker
spec:
  clusterIP: None
  selector:
    app: spark-worker
  ports:
    - port: 8081
      name: web-ui
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-worker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spark-worker
  template:
    metadata:
      labels:
        app: spark-worker
    spec:
      containers:
      - name: spark-worker
        image: apache/spark:3.4.1
        command: ["/opt/spark/bin/spark-class"]
        args: ["org.apache.spark.deploy.worker.Worker", "spark://spark-master:7077"]
        ports:
        - containerPort: 8081
          name: web-ui
        env:
        - name: SPARK_WORKER_CORES
          value: "2"
        - name: SPARK_WORKER_MEMORY
          value: "4g"
        - name: SPARK_WORKER_WEBUI_PORT
          value: "8081"
        resources:
          requests:
            memory: "4Gi"
            cpu: "2000m"
          limits:
            memory: "8Gi"
            cpu: "4000m"