apiVersion: batch/v1
kind: Job
metadata:
  name: spark-cluster-app
spec:
  template:
    metadata:
      labels:
        app: spark-cluster-app
    spec:
      restartPolicy: Never
      containers:
      - name: spark-submit
        image: laidung/traffic-spark-app:v1
        imagePullPolicy: Always
        command: ["/opt/spark/bin/spark-submit"]
        args:
          - "--master"
          - "spark://spark-master:7077"
          - "--deploy-mode"
          - "client"
          - "--packages"
          - "org.apache.spark:spark-sql-kafka-0-10_2.12:3.4.1,org.mongodb.spark:mongo-spark-connector_2.12:10.2.1"
          - "--conf"
          - "spark.executor.instances=3"
          - "--conf"
          - "spark.executor.memory=4g"
          - "--conf"
          - "spark.executor.cores=2"
          - "--conf"
          - "spark.driver.memory=2g"
          - "--py-files"
          - "/app/util.py"
          - "/app/main.py"
        env:
          - name: KAFKA_BROKER
            value: "my-kafka:9092"
          - name: TOPIC_NAME
            value: "traffic_data"
          - name: MONGO_URI
            value: "mongodb://root:bigdataproject@my-mongodb:27017/traffic_db?authSource=admin"
          - name: MINIO_ENDPOINT
            value: "my-minio:9000"
          - name: MINIO_ROOT_USER
            value: "bigdataproject"
          - name: MINIO_ROOT_PASSWORD
            value: "bigdataproject"