apiVersion: batch/v1
kind: Job
metadata:
  name: traffic-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traffic-producer
  template:
    metadata:
      labels:
        app: traffic-producer
    spec:
      containers:
      - name: producer
        image: anvu1204/traffic-producer:v6
        imagePullPolicy: Always
        env:
        - name: KAFKA_BROKER
          value: "my-kafka:9092"
        - name: MINIO_ENDPOINT
          value: "my-minio:9000"
        - name: MINIO_ACCESS_KEY
          value: "bigdataproject"
        - name: MINIO_SECRET_KEY
          value: "bigdataproject"
        
        - name: CAM_MODE
          value: "demo"