apiVersion: apps/v1
kind: Deployment
metadata:
  name: metabase
  labels:
    app: metabase
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metabase
  template:
    metadata:
      labels:
        app: metabase
    spec:
      containers:
      - name: metabase
        image: metabase/metabase:latest
        ports:
        - containerPort: 3000
        resources:
          limits:
            memory: "2048Mi"
            cpu: "1000m"
          requests:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: MB_DB_FILE
          value: "/metabase-data/metabase.db"
        volumeMounts:
        - name: metabase-storage
          mountPath: /metabase-data
      volumes:
      - name: metabase-storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: metabase-service
spec:
  selector:
    app: metabase
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort